### Create patinent request
POST http://localhost:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "abc xyz",
  "email": "abc@xyz.com",
  "address": "abc, Main bill",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2024-11-28"

}

###