### Create patinent request
POST http://localhost:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "test User",
  "email": "newUser@email.com",
  "address": "Hill road, Mumbai, Maharashtra",
  "dateOfBirth": "2002-02-02",
  "registeredDate": "2026-02-02"

}

###