### Create patinent request
PUT http://localhost:4004/api/patients/9780f5d4-53f4-4520-adbf-8ed0d2165325
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "John Doe 33",
  "email": "updatedEmail@example.com",
  "address": "abc, Main Street",
  "dateOfBirth": "1995-09-09"
}

###